### ISSUE TITLE
[테스팅] 재구현

### ISSUE THREAD

**Issue by ghk829** [yoonjong12/pinsage#1]
안녕하세요, 좋은 repository를 찾아서 연락드리네요.
해당 모델을 제 형식에 맞게 run해보고 싶은데요.
dataset 혹은 movielens로라도 재구현할 수 있는 방법이 있을까요?

**Comment by yoonjong12** [comment]
아직 부족하고, 단체 프로젝트를 위해서 코딩했기 때문에 데이터 공유도 어렵습니다만,
DGL에서 제공하는 Pinsage 예시를 참고하시면 어떠실까 합니다
 
https://github.com/dmlc/dgl/tree/master/examples/pytorch/pinsage 
 
상위 링크에서는 Pinsage모델 및 MovieLens 1M 데이터를 사용하여 실제로 학습을 해볼 수 있습니다
Evaluation을 제외하고 학습을 위한 코드는 예제와 동일합니다.
 
혹시라도 다른 궁금한 점이 있으시다면 말씀부탁드립니다.
