### ISSUE TITLE
Vivino Data

### ISSUE THREAD

**Issue by arijitthegame** [yoonjong12/pinsage#2]
Is there some place where I can find this Vivino data?

**Comment by yoonjong12** [comment]
I'm sorry, but vivino data is collected by my team members. So please understand that I can't share as much as I want.
 
Instead, why don't you experiment by referring to the link below? I studied this example and proceeded with the project.
You can train PinSAGE with Movielens 1M data.
Link:  https://github.com/dmlc/dgl/tree/master/examples/pytorch/pinsage
 
Let me know if you have any concerns.
 
-----Original Message-----

**Comment by arijitthegame** [comment]
Thank you.
