### ISSUE TITLE
Applying Inference in MovieLense dataset

### ISSUE THREAD

**Issue by geo47** [yoonjong12/pinsage#4]
Hi @yoonjong12 

Nice work.

I want some help regarding implementing inferencing in the PinSAGE model implemented in (https://github.com/dmlc/dgl/tree/master/examples/pytorch/pinsage)

I appreciate it if you could help in implementing inferencing.

Thanks

**Comment by geo47** [comment]
이것 좀 봐주시겠어요? 
나는 이것에 붙어 있고 해결책을 알아낼 수 없습니다.

**Comment by yoonjong12** [comment]
Hello. What kind of problem are you having?

**Comment by geo47** [comment]
Hi @yoonjong12 ,

I want to run your project on my dataset but I need to know the data format you prepare for this project.
Could you please tell me the schema of your dataset?

**Comment by yoonjong12** [comment]
First, I used wine review data. In the review of wine consumed by a user, all wines are embedded considering ratings, reviews, etc.

Essential data includes:
| Feature | Desc | Type | 
|------------|----------|----------|
| user ID | user ID who wrote the review | int64 |
| wine ID | ID of the wine reviewd by the user | int64 |
| rate | rate of the wine | float64 |

Then you can add as many features as you want about what you want to embed.
I added the taste and acidity of wine, alcohol, grape, etc.

I don't know if it'll help, but I'll share the code that's tailored for my project. The code is about pre-processing review data and creating a pickle file just before entering it into the pinage module. Please refer to it if necessary.

https://github.com/tobigs-reco-conf-1314/Tommelier/blob/main/Models/GCN/process_wine.py

**Comment by BoPengGit** [comment]
Hi @yoonjong12 ,

Great work. Do you have the link to the dataset that you used?

Thanks.

**Comment by yoonjong12** [comment]
I updated a part of the data I used by putting it in a 'data' folder.

And, If you don't mind, please check 'process_wine.py' for preprocess data.

But, it's a small part of the entire data, so please understand that the desired performance may not come out.
