### ISSUE TITLE
wine Data에 조금 수정이 필요 해 보입니다.

### ISSUE THREAD

**Issue by namjunwoo223** [yoonjong12/pinsage#5]
우선, 정말 귀중한 자료와 코드를 공유 해 주신것에 대해 감사합니다.

Data Process 코드인 process_wine.py에 json처리에 조금 수정이 필요해보여서 전달 드립니다.

process_wine.py
users = pd.DataFrame(user_json) -> users = pd.DataFrame(user_json["data"])
items = pd.DataFrame(item_json) -> items = pd.DataFrame(item_json["data"])
columns = ['wine_id', 'name', 'rating_average', 'body', 'acidity', 'alcohol', 'grapes_id'] -> columns = ['wine_id', 'name', 'rating_average', 'body', 'acidity_x', 'alcohol', 'grapes_id']
items['wine_feats'] = list(items[['rating_average', 'body', 'acidity' ,'alcohol']].values) -> items['wine_feats'] = list(items[['rating_average', 'body', 'acidity_x' ,'alcohol']].values)

train,test 자료 중 like가 1이였던 컬럼만 남아있었을거라 추측하여 like관련 컬럼처리 삭제.

**Comment by yoonjong12** [comment]
@namjunwoo223 
피드백 감사드립니다. 제대로 검토하지 않고 코드를 공유드한 것 같아 죄송스럽네요 ㅠㅠ

그런데, 마지막 부분은 조금 짚고 넘어가야 할 것 같습니다.
like 변수의 존재의의는 유저가 나쁘게 평가했던 아이템도 추천해줄 것이냐는 관점의 차이를 나타내는 것입니다.  따라서 like를 만드는 코드를 추가했고, 나머지는 각자의 판단에 따라서 like를 활용하느냐를 결정하면 될 것 같습니다.
