### ISSUE TITLE
dataset 

### ISSUE THREAD

**Issue by riyaj8888** [yoonjong12/pinsage#7]
hi,
thanks for sharing preprocess function.

could you tell me what is the purpose of timestamp column in dataset ?
because in movielens they have timestamp column and they use it to predict most recent users iteractions.
would appreciate your insight on this.

**Comment by yoonjong12** [comment]
Simply, it is an index for dividing the train set and test set in a ratio of 8:2. In fact, it was actually the date the review was written, but it was simply numbered in order of writing.
The reason for this was to prevent future reviews from training and to prevent past reviews from being predicated.

**Comment by riyaj8888** [comment]
thanks for reply.

I tried your repo when i am running this command to train model. its using cpu even i set the device to cuda:0.
do u know where i m making mistake.
and my whole training got stucked .
`python model.py -d ./data_processed/data.pkl --num-epochs 1 --num-workers 0 --device cuda:0 --hidden-dims 64`

**Comment by riyaj8888** [comment]
thanks .
could you guide me , how to do inference on trained graph model.?

**Comment by yoonjong12** [comment]
You can use evaluation.py to check the model's performance. If you want to use the trained model for other purposes, refer to README.md and derive the most similar 'topk' item from 'h_item', the embedding vector of all nodes.

**Comment by riyaj8888** [comment]
Ok.
I have tried to train on your wine dataset.
During training i am getting precision:0.05,recall:0.048 .
Did you also get similar number?
I didn't make any changes at all, except default arguments in train function

**Comment by riyaj8888** [comment]
in the evaluation.py we need to pass item_embdding_path as input argument .
but during training there is nothing to save embedding in pickel file.
so from where this embedding pickle file to be pass?
`            h_item = evaluation.get_all_emb(gnn, g.ndata['id'][item_ntype], data_dict['textset'], item_ntype, neighbor_sampler, args.batch_size, device)
`
`    with open(args.item_embedding_path, 'rb') as f:
        emb = torch.FloatTensor(pickle.load(f))`

**Comment by yoonjong12** [comment]
> Ok. I have tried to train on your wine dataset. During training i am getting precision:0.05,recall:0.048 . Did you also get similar number? I didn't make any changes at all, except default arguments in train function

In fact, the data I shared is only a part of the total data, so the performance is bound to be low. Think of the wine data as a way to check if the code is working.


> in the evaluation.py we need to pass item_embdding_path as input argument . but during training there is nothing to save embedding in pickel file. so from where this embedding pickle file to be pass? ` h_item = evaluation.get_all_emb(gnn, g.ndata['id'][item_ntype], data_dict['textset'], item_ntype, neighbor_sampler, args.batch_size, device)` ` with open(args.item_embedding_path, 'rb') as f: emb = torch.FloatTensor(pickle.load(f))`

pinage is an inductive learning model. That means, training is the GNN model that generates the representation of the raw graph, and model.py is the code that trains and stores the model. If you have finished training, use raw graph and trained GNN and generate representation with get_all_emb function.
